name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_run:
    workflows: ["Update StabilityMatrix"]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v14

      - name: Build package
        run: nix build

      - name: Smoke test
        run: test -x ./result/bin/stability-matrix
